#!/usr/bin/env python3
"""Import commonlyusedwords.com's "2000 most common Maltese words" as an OPTIONAL,
quarantined deck.

⚠️  Read this before using it.

That list is a machine translation of an English frequency list, not a Maltese
frequency list, and it contains real errors:

    #7    pulzieri   → glossed "in"        (actually *inches*)
    #62   sal-bott   → glossed "to can"    (the modal verb was read as a tin can)
    #75   ġust       → glossed "just"      (calque; Maltese would use `biss`/`eżatt`)
    #2    li tkun    → glossed "to be"     (a subordinate clause, not a headword)

So the curated `data/core_vocab.tsv` deck is what the app teaches by default. This
script exists for coverage: it pulls the list, drops entries that fail the sanity
checks below, and writes `data/frequency_import.tsv` at tier 4 so imported items
only ever surface *after* the curated core. Every row carries a `note` marking it
unverified.

    python scripts/import_frequency_list.py            # fetch and filter
    python scripts/import_frequency_list.py --all      # keep flagged rows too
    python scripts/import_frequency_list.py --limit 500
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "frequency_import.tsv"
URL = "https://commonlyusedwords.com/2000-most-common-maltese-words/"

# Entries whose Maltese side is one of these are artefacts of the machine
# translation (English infinitive markers, clause fragments) rather than words.
BAD_PREFIXES = ("li tkun", "li jkollha", "biex ", "li ")
# Known bad glosses, keyed by the Maltese form.
KNOWN_BAD = {"pulzieri", "sal-bott", "ġust", "se"}

MALTESE_CHARS = re.compile(r"^[a-zA-ZàèìòùċġħżĊĠĦŻ' \-–]+$")


def fetch() -> str:
    import httpx

    r = httpx.get(URL, timeout=60, follow_redirects=True,
                  headers={"user-agent": "speak-maltese/1.0 (personal study tool)"})
    r.raise_for_status()
    return r.text


def parse(html: str) -> list[tuple[int, str, str]]:
    rows: list[tuple[int, str, str]] = []
    for m in re.finditer(r"<tr[^>]*>(.*?)</tr>", html, re.S | re.I):
        cells = re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", m.group(1), re.S | re.I)
        if len(cells) < 3:
            continue
        clean = [re.sub(r"<[^>]+>", "", c) for c in cells[:3]]
        clean = [re.sub(r"\s+", " ", c).replace("&nbsp;", " ").strip() for c in clean]
        if not clean[0].isdigit():
            continue
        rows.append((int(clean[0]), clean[1], clean[2]))
    return rows


def suspect(mt: str, en: str) -> str | None:
    low = mt.lower().strip()
    if low in KNOWN_BAD:
        return "known mistranslation"
    if any(low.startswith(p) for p in BAD_PREFIXES):
        return "clause fragment, not a headword"
    if not MALTESE_CHARS.match(mt):
        return "non-Maltese characters"
    if len(low) < 2:
        return "too short"
    if low.count(" ") >= 3:
        return "looks like a sentence"
    return None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true", help="keep rows that fail the checks")
    ap.add_argument("--limit", type=int, default=2000)
    ap.add_argument("--start", type=int, default=1, help="skip the first N ranks")
    args = ap.parse_args()

    print(f"→ fetching {URL}")
    rows = parse(fetch())
    if not rows:
        print("✗ no table rows found — the page layout probably changed", file=sys.stderr)
        return 1
    print(f"→ parsed {len(rows)} rows")

    kept, dropped = [], 0
    seen: set[str] = set()
    for rank, mt, en in rows:
        if rank < args.start or rank > args.limit:
            continue
        reason = suspect(mt, en)
        if reason and not args.all:
            dropped += 1
            continue
        key = mt.lower()
        if key in seen:
            continue
        seen.add(key)
        kept.append({
            "id": f"f{rank:04d}",
            "mt": mt,
            "en": en,
            "pos": "",
            "tier": 4,
            "topic": "frequency",
            "note": f"rank {rank} · unverified machine translation"
                    + (f" · flagged: {reason}" if reason else ""),
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8", newline="") as fh:
        fh.write("# Auto-generated by scripts/import_frequency_list.py — UNVERIFIED.\n")
        fh.write("# Source is a machine translation; check anything before trusting it.\n")
        w = csv.DictWriter(fh, delimiter="\t",
                           fieldnames=["id", "mt", "en", "pos", "tier", "topic", "note"])
        w.writeheader()
        w.writerows(kept)

    print(f"✓ wrote {len(kept)} rows to {OUT.relative_to(ROOT)} ({dropped} dropped)")
    print("  Restart the server to load them; they sit at tier 4, behind the curated core.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
